server:
  port: 3380

spring:
  application:
    # This ends up as the service name in zipkin
    name: ms-zipkin
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    enabled: true

logging:
  file: myapplication.log

#logging:
#  level:
#    org.springframework.cloud.consul: DEBUG
#  pattern:
#    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'

